-- MySQL Script generated by MySQL Workbench
-- 10/31/17 15:16:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BeWaterMelon
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BeWaterMelon` ;

-- -----------------------------------------------------
-- Schema BeWaterMelon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BeWaterMelon` DEFAULT CHARACTER SET utf8 ;
USE `BeWaterMelon` ;

-- -----------------------------------------------------
-- Table `BeWaterMelon`.`ppl_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`ppl_user` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`ppl_user` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `bio` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `web_UNIQUE` (`link` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`ppl_phd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`ppl_phd` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`ppl_phd` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `thesis_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`ppl_postdoc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`ppl_postdoc` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`ppl_postdoc` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`ppl_visitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`ppl_visitor` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`ppl_visitor` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `doctor` VARCHAR(45) BINARY NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `web_UNIQUE` (`link` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`ppl_past_phd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`ppl_past_phd` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`ppl_past_phd` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `thesis_date` YEAR NOT NULL,
  `thesis_name` VARCHAR(200) NOT NULL,
  `thesis_link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`ppl_collaborator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`ppl_collaborator` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`ppl_collaborator` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `doctor` VARCHAR(45) BINARY NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`pub_journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`pub_journal` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`pub_journal` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(100) NOT NULL,
  `publication_name` VARCHAR(200) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `publication_date` YEAR NOT NULL,
  `online_issn` VARCHAR(9) NOT NULL,
  `link` VARCHAR(500) NULL,
  `print_issn` VARCHAR(9) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`pub_conference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`pub_conference` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`pub_conference` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(100) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `link_UNIQUE` (`link` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`pub_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`pub_book` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`pub_book` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(100) NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `editorial` VARCHAR(100) NOT NULL,
  `year` YEAR NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(17) NOT NULL,
  `link` VARCHAR(500) NULL,
  `physical_id` VARCHAR(8) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `physical_id_UNIQUE` (`physical_id` ASC),
  UNIQUE INDEX `link_UNIQUE` (`link` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`act_editorial_board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`act_editorial_board` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`act_editorial_board` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `journal_name` VARCHAR(100) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `online_issn` VARCHAR(9) NOT NULL,
  `online_issn_year` YEAR NOT NULL,
  `h_index` VARCHAR(45) NOT NULL,
  `sjr` FLOAT(3) NOT NULL,
  `sjr_year` YEAR NOT NULL,
  `sjr_quartile` VARCHAR(2) NOT NULL,
  `print_issn` VARCHAR(9) NULL,
  `impact_factor` FLOAT(3) NULL,
  `impact_factor_quartile` VARCHAR(2) NULL,
  `impact_factor_year` YEAR NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`act_journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`act_journal` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`act_journal` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `online_issn` VARCHAR(9) NOT NULL,
  `online_issn_year` YEAR NOT NULL,
  `impacr_factor` FLOAT(3) NOT NULL,
  `impact_factor_quartile` VARCHAR(2) NOT NULL,
  `impact_factor_year` YEAR NOT NULL,
  `print_issn` VARCHAR(9) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`act_conference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`act_conference` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`act_conference` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `acronym` VARCHAR(45) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`res_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`res_project` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`res_project` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `scheduling` VARCHAR(45) NOT NULL,
  `sponsor_link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`res_contract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`res_contract` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`res_contract` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `scheduling` VARCHAR(45) NOT NULL,
  `sponsor_link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`res_patent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`res_patent` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`res_patent` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `year` YEAR NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`col_member_of`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`col_member_of` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`col_member_of` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`col_colleague`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`col_colleague` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`col_colleague` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `doctor` VARCHAR(45) BINARY NOT NULL,
  `department` VARCHAR(100) NOT NULL,
  `position` VARCHAR(100) NOT NULL,
  `company` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`col_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`col_group` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`col_group` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `department` VARCHAR(100) NOT NULL,
  `company` VARCHAR(100) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`col_institution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`col_institution` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`col_institution` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`col_company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`col_company` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`col_company` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`pro_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`pro_product` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`pro_product` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  `detailed_description` VARCHAR(5000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`cou_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`cou_subject` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`cou_subject` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `teacher` INT(5) NOT NULL,
  `abbreviation` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_teacher_idx` (`teacher` ASC),
  CONSTRAINT `subject_teacher`
    FOREIGN KEY (`teacher`)
    REFERENCES `BeWaterMelon`.`ppl_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`cou_degree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`cou_degree` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`cou_degree` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`cou_course_degree_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`cou_course_degree_subject` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`cou_course_degree_subject` (
  `id_degree` INT(5) NOT NULL,
  `id_subject` INT(5) NOT NULL,
  `year` YEAR NOT NULL,
  PRIMARY KEY (`id_degree`, `id_subject`, `year`),
  INDEX `degree_idx` (`id_degree` ASC),
  INDEX `subject_idx` (`id_subject` ASC),
  CONSTRAINT `degree`
    FOREIGN KEY (`id_degree`)
    REFERENCES `BeWaterMelon`.`cou_degree` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `subject`
    FOREIGN KEY (`id_subject`)
    REFERENCES `BeWaterMelon`.`cou_subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`res_project_participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`res_project_participant` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`res_project_participant` (
  `id` INT(5) NOT NULL,
  `participant` VARCHAR(200) NOT NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`, `participant`),
  CONSTRAINT `project_participant`
    FOREIGN KEY (`id`)
    REFERENCES `BeWaterMelon`.`res_project` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`act_conference_year`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`act_conference_year` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`act_conference_year` (
  `id` INT(5) NOT NULL,
  `year` YEAR NOT NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`, `year`),
  CONSTRAINT `conference_year`
    FOREIGN KEY (`id`)
    REFERENCES `BeWaterMelon`.`act_conference` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`res_contract_participant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`res_contract_participant` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`res_contract_participant` (
  `id` INT(5) NOT NULL,
  `participant` VARCHAR(200) NOT NULL,
  `link` VARCHAR(500) NULL,
  PRIMARY KEY (`id`, `participant`),
  CONSTRAINT `contract_participant`
    FOREIGN KEY (`id`)
    REFERENCES `BeWaterMelon`.`res_contract` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeWaterMelon`.`pre_press`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BeWaterMelon`.`pre_press` ;

CREATE TABLE IF NOT EXISTS `BeWaterMelon`.`pre_press` (
  `id` INT(5) NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `source` VARCHAR(100) NOT NULL,
  `link` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
